on:
#  schedule:
#  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v7
      - name: Archive repo
        id: archive
        run: |
          tmpfile=$(mktemp /tmp/archive.XXXXXX)
          echo "$tmpfile"
          echo "ARCHIVE_FILE=${tmpfile}" >> "$GITHUB_OUTPUT"
          git archive --format=zip --output="$tmpfile" HEAD
      - name: Create build from archive
        id: build
        env:
          ARCHIVE_FILE: ${{ steps.archive.outputs.ARCHIVE_FILE }}
        run: |
          echo "$ARCHIVE_FILE"
