on:
#  schedule:
#  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Archive repo
        run: |
          {
            echo 'GIT_ARCHIVE<<EOF'
            git archive HEAD
            echo EOF
          }  >> "$GITHUB_ENV"
      - name: Create build from archive
        run: |
          echo "$GIT_ARCHIVE"
